select*
from customer_data;
select count(*)
from customer_data;

-- Q1. What is the total revenue generated by male vs. female customers?

SELECT gender, SUM(purchase_amount) AS reveneu
FROM customer_data
GROUP BY gender
ORDER BY gender DESC;


-- Q2. Which customers used a discount but still spent more than the average purchase amount an their total number?

SELECT AVG(purchase_amount)
FROM customer_data;

SELECT customer_id, purchase_amount
FROM customer_data
WHERE discount_applied = 'Yes' AND purchase_amount > (SELECT AVG(purchase_amount) FROM customer_data);


SELECT COUNT(*)
FROM (
	SELECT customer_id, purchase_amount
FROM customer_data
WHERE discount_applied = 'Yes' AND purchase_amount > (SELECT AVG(purchase_amount) FROM customer_data)) AS filtered_data;


-- Q3. Which are the top 5 products with the highest average review rating?

SELECT item_purchased, AVG(review_rating) AS avg_rating
FROM customer_data
GROUP BY item_purchased
ORDER BY avg_rating DESC
LIMIT 5;


-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.


SELECT shipping_type, AVG(purchase_amount) AS avg_purchase_type
FROM customer_data
WHERE shipping_type in ('Standard', 'Express')
GROUP BY shipping_type;


-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.


SELECT subscription_status,
	COUNT(customer_id) AS total_customer,
	AVG(purchase_amount) AS avg_spend, 
	SUM(purchase_amount) AS total_reveneu
FROM customer_data
GROUP BY subscription_status;


-- Q6 Which 5 products have the highest percentage of purchases with discounts applied?

SELECT item_purchased, COUNT(*) AS total_purchased,
	SUM(CASE WHEN discount_applied = 'yes' THEN 1 ELSE 0 END) AS discount_purchases,
    (SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*)) * 100 AS discount_percentage
FROM customer_data
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;


-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.

WITH customer_type AS (
	SELECT customer_id, previous_purchases,
    CASE 
		WHEN previous_purchases = 1 THEN 'New'
        WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
        ELSE 'Loyal'
	END AS customer_segment
FROM customer_data
)
SELECT customer_segment, COUNT(*) AS total_customers
FROM customer_type
GROUP BY customer_segment
ORDER BY total_customers DESC;


-- Q8. What are the top 3 most purchased products within each category?

WITH item_counts AS(
	SELECT category, item_purchased, COUNT(customer_id) AS total_orders,
    ROW_NUMBER() OVER(partition by category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer_data
    GROUP BY  category, item_purchased
)

SELECT item_rank, category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <= 3
ORDER BY category, total_orders DESC;


-- 9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?


SELECT subscription_status, COUNT(customer_id) AS repeat_buyers
FROM customer_data
WHERE previous_purchases > 5
GROUP BY subscription_status;


-- 10. What is the revenue contribution of each age group?

SELECT age_group, SUM(purchase_amount) AS total_reveneu
FROM customer_data
GROUP BY age_group
ORDER BY total_reveneu DESC;






















































































